#!/usr/bin/env bash
set -euo pipefail

ROOT="${KONTEXT_ROOT:-/opt/kontext}"
MEM0_ROOT="${MEM0_ROOT:-/opt/mem0-remote-mcp}"
OUTDIR="${KONTEXT_OBSERVER_OUTDIR:-$ROOT/reports/cutover-observer}"
LOG_PATH="$OUTDIR/_kontext_cutover_observer.log"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"

mkdir -p "$OUTDIR"
exec >>"$LOG_PATH" 2>&1

echo "[$(date -u --iso-8601=seconds)] kontext cutover observer start stamp=$STAMP"

USAGE_REPORT="$OUTDIR/mem0-usage-$STAMP.json"
CLIENT_STATUS="$OUTDIR/mem0-client-status-$STAMP.json"
OBSERVER_JSON="$OUTDIR/kontext-cutover-observer-$STAMP.json"
OBSERVER_MD="$OUTDIR/kontext-cutover-observer-$STAMP.md"
OBSERVER_STDOUT="$OUTDIR/last-stdout.json"
HISTORY_LOG="$OUTDIR/observer-history.jsonl"
RETENTION_REPORT="$OUTDIR/retrieval-query-retention-$STAMP.json"
RETENTION_LATEST="$OUTDIR/retrieval-query-retention-latest.json"
OB1_RETRIEVAL_QUALITY_REPORT="$OUTDIR/ob1-retrieval-quality-gate-$STAMP.json"
OB1_RETRIEVAL_QUALITY_LATEST="$OUTDIR/ob1-retrieval-quality-gate-latest.json"
OB1_RETRIEVAL_QUALITY_TIMEOUT_SECONDS="${KONTEXT_OB1_RETRIEVAL_TIMEOUT_SECONDS:-120}"
SHADOW_COMPARISON_LOG="$MEM0_ROOT/data/mem0-kontext-shadow-comparison.jsonl"
WRITE_AUDIT_LOG="$MEM0_ROOT/data/mem0-kontext-write-audit.jsonl"
ROLLBACK_DRILL_REPORT="$ROOT/reports/rollback-drill/latest.json"

latest_matching_report() {
  local override="$1"
  shift
  if [ -n "$override" ]; then
    printf '%s\n' "$override"
    return 0
  fi
  local pattern latest
  for pattern in "$@"; do
    latest="$(
      find "$ROOT/reports" -maxdepth 1 -type f -name "$pattern" -printf '%T@ %p\n' 2>/dev/null \
        | sort -nr \
        | head -n 1 \
        | cut -d' ' -f2-
    )"
    if [ -n "$latest" ]; then
      printf '%s\n' "$latest"
      return 0
    fi
  done
  printf '\n'
}

SCORECARD_REPORT="$(latest_matching_report "${KONTEXT_OBSERVER_SCORECARD:-}" "kontext-goal-scorecard-*.json")"
CUTOVER_READINESS_REPORT="$(latest_matching_report "${KONTEXT_OBSERVER_CUTOVER_READINESS:-}" "kontext-cutover-readiness-*.json")"
if [ -z "$SCORECARD_REPORT" ] || [ -z "$CUTOVER_READINESS_REPORT" ]; then
  echo "missing cutover observer inputs scorecard=$SCORECARD_REPORT readiness=$CUTOVER_READINESS_REPORT"
  exit 2
fi

cd "$MEM0_ROOT"

python3 usage_report_cli.py \
  --audit-log "$MEM0_ROOT/data/mem0-mcp-audit.jsonl" \
  --retrieval-log "$MEM0_ROOT/data/mem0-mcp-retrieval.jsonl" \
  --hook-log "$MEM0_ROOT/data/mem0-mcp-hooks.jsonl" \
  --recent-limit "${KONTEXT_OBSERVER_RECENT_LIMIT:-5000}" \
  --json > "$USAGE_REPORT"

python3 client_compliance_status_cli.py \
  --audit-log "$MEM0_ROOT/data/mem0-mcp-audit.jsonl" \
  --retrieval-log "$MEM0_ROOT/data/mem0-mcp-retrieval.jsonl" \
  --hook-log "$MEM0_ROOT/data/mem0-mcp-hooks.jsonl" \
  --expected-origin "${KONTEXT_OBSERVER_EXPECTED_ORIGIN:-codex}" \
  --recent-limit "${KONTEXT_OBSERVER_RECENT_LIMIT:-5000}" \
  --json > "$CLIENT_STATUS"

set +e
timeout "$OB1_RETRIEVAL_QUALITY_TIMEOUT_SECONDS" docker exec -e PYTHONPATH=/app kontext python /app/scripts/kontext_ob1_retrieval_quality_gate.py \
  --cases /app/eval/ob1_retrieval_quality_cases.json \
  --top-k "${KONTEXT_OB1_RETRIEVAL_TOP_K:-10}" > "$OB1_RETRIEVAL_QUALITY_REPORT"
OB1_RETRIEVAL_QUALITY_CODE=$?
set -e

OB1_RETRIEVAL_QUALITY_FATAL="$OB1_RETRIEVAL_QUALITY_CODE"
if [ "$OB1_RETRIEVAL_QUALITY_CODE" -eq 124 ] || [ "$OB1_RETRIEVAL_QUALITY_CODE" -eq 137 ] || [ ! -s "$OB1_RETRIEVAL_QUALITY_REPORT" ]; then
  python3 - "$OB1_RETRIEVAL_QUALITY_REPORT" "$OB1_RETRIEVAL_QUALITY_CODE" "$OB1_RETRIEVAL_QUALITY_TIMEOUT_SECONDS" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
code = int(sys.argv[2])
timeout_seconds = int(sys.argv[3])
path.write_text(json.dumps({
    "ok": False,
    "mode": "ob1-retrieval-quality-gate",
    "runs_model_calls": False,
    "top_k": None,
    "summary": {"cases": 0, "passed": 0, "failed": 1, "pass_rate": 0.0},
    "groups": {},
    "cases": [
        {
            "name": "ob1_retrieval_quality_gate",
            "group": "operational",
            "query_hash": "unavailable",
            "passed": False,
            "first_satisfying_rank": None,
            "max_rank": None,
            "result_count": 0,
            "top_result_hashes": [],
            "failed_reasons": ["timeout_or_error"],
        }
    ],
    "error": {"returncode": code, "timeout_seconds": timeout_seconds},
    "notes": ["Fallback report generated by the observer runner after the OB1 retrieval quality gate timed out or emitted no report."],
}, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
PY
fi

if [ -s "$OB1_RETRIEVAL_QUALITY_REPORT" ] && { [ "$OB1_RETRIEVAL_QUALITY_CODE" -eq 124 ] || [ "$OB1_RETRIEVAL_QUALITY_CODE" -eq 137 ]; }; then
  echo "[$(date -u --iso-8601=seconds)] OB1 retrieval quality fallback report present; suppressing fatal exit code=$OB1_RETRIEVAL_QUALITY_CODE"
  OB1_RETRIEVAL_QUALITY_FATAL=0
fi

if [ -f "$OB1_RETRIEVAL_QUALITY_REPORT" ]; then
  cp "$OB1_RETRIEVAL_QUALITY_REPORT" "$OB1_RETRIEVAL_QUALITY_LATEST"
fi

set +e
python3 "$ROOT/scripts/kontext_cutover_observer.py" \
  --scorecard "$SCORECARD_REPORT" \
  --cutover-readiness "$CUTOVER_READINESS_REPORT" \
  --usage-report "$USAGE_REPORT" \
  --client-status "$CLIENT_STATUS" \
  --ob1-retrieval-quality-report "$OB1_RETRIEVAL_QUALITY_REPORT" \
  --shadow-comparison-log "$SHADOW_COMPARISON_LOG" \
  --write-audit-log "$WRITE_AUDIT_LOG" \
  --rollback-drill-report "$ROLLBACK_DRILL_REPORT" \
  --expected-origin "${KONTEXT_OBSERVER_EXPECTED_ORIGIN:-codex}" \
  --label "${KONTEXT_OBSERVER_LABEL:-codex-kontext-primary-canary}" \
  --max-input-age-hours "${KONTEXT_OBSERVER_MAX_INPUT_AGE_HOURS:-48}" \
  --output "$OBSERVER_JSON" \
  --markdown-output "$OBSERVER_MD" \
  --history-log "$HISTORY_LOG" > "$OBSERVER_STDOUT"
OBSERVER_CODE=$?
set -e

OBSERVER_FATAL="$OBSERVER_CODE"
if [ -f "$OBSERVER_JSON" ]; then
  cp "$OBSERVER_JSON" "$OUTDIR/latest.json"
fi
if [ -f "$OBSERVER_MD" ]; then
  cp "$OBSERVER_MD" "$OUTDIR/latest.md"
fi
if [ -s "$OBSERVER_JSON" ] && [ "$OBSERVER_CODE" -ne 0 ]; then
  echo "[$(date -u --iso-8601=seconds)] cutover observer report present; suppressing fatal exit code=$OBSERVER_CODE"
  OBSERVER_FATAL=0
fi

RETENTION_APPLY_ARGS=()
if [ "${KONTEXT_RETRIEVAL_RETENTION_APPLY:-0}" = "1" ]; then
  RETENTION_APPLY_ARGS=(--apply)
fi

set +e
docker exec -e PYTHONPATH=/app kontext python /app/scripts/retrieval_query_retention.py \
  --keep-days "${KONTEXT_RETRIEVAL_RETENTION_KEEP_DAYS:-30}" \
  --max-delete "${KONTEXT_RETRIEVAL_RETENTION_MAX_DELETE:-5000}" \
  "${RETENTION_APPLY_ARGS[@]}" > "$RETENTION_REPORT"
RETENTION_CODE=$?
set -e

if [ -f "$RETENTION_REPORT" ]; then
  cp "$RETENTION_REPORT" "$RETENTION_LATEST"
fi

if command -v jq >/dev/null 2>&1 && [ -f "$OBSERVER_JSON" ]; then
  jq -c '{ok:.ok,recommendation:.recommendation,summary:.summary,transition_decision:.transition_assessment.decision,remaining_work_keys:.transition_assessment.remaining_work_keys,attention_items:.attention_items}' "$OBSERVER_JSON"
else
  python3 - "$OBSERVER_JSON" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
if path.exists():
    report = json.loads(path.read_text(encoding="utf-8"))
    print(json.dumps({
        "ok": report.get("ok"),
        "recommendation": report.get("recommendation"),
        "summary": report.get("summary"),
        "transition_decision": (report.get("transition_assessment") or {}).get("decision"),
        "remaining_work_keys": (report.get("transition_assessment") or {}).get("remaining_work_keys"),
        "attention_items": report.get("attention_items"),
    }, sort_keys=True))
PY
fi

echo "[$(date -u --iso-8601=seconds)] retrieval query retention finish code=$RETENTION_CODE"
echo "[$(date -u --iso-8601=seconds)] OB1 retrieval quality finish code=$OB1_RETRIEVAL_QUALITY_CODE"
echo "[$(date -u --iso-8601=seconds)] kontext cutover observer finish code=$OBSERVER_CODE"
if [ "$OB1_RETRIEVAL_QUALITY_FATAL" -ne 0 ]; then
  exit "$OB1_RETRIEVAL_QUALITY_FATAL"
fi
if [ "$OBSERVER_FATAL" -ne 0 ]; then
  exit "$OBSERVER_FATAL"
fi
exit "$RETENTION_CODE"
